platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'AFNetworking'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'DAKeyboardControl', '~> 2.3'
pod 'UIAlertView-Blocks', '0.0.1'
pod 'SVProgressHUD', :head
pod 'SVPullToRefresh'
pod 'TTTAttributedLabel'
# pod 'CLImageEditor/AllTools', :git => 'https://github.com/ndbinh99/CLImageEditor.git'